### ISSUE TITLE
colab에서 구현할 수 있나요?

### ISSUE THREAD

**Issue by boozesounds** [quantylab/rltrader#100]
제가 코랩을 이용하는데, 코랩에서도 구현 가능한가요..?
파일이 많이 나누어져있어서 어렵네요..

**Comment by ggokka** [comment]
tensorflow 1.15.2 버전을 써야 하는데요. colab에서는 다운버전을 어떻게 하는지 모르겠네요.

2021-06-13 01:39:03.204078: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    from learners import ReinforcementLearner, DQNLearner, \
  File "/content/drive/My Drive/quantylab/rltrader/learners.py", line 11, in <module>
    from networks import Network, DNN, LSTMNetwork, CNN
  File "/content/drive/My Drive/quantylab/rltrader/networks.py", line 23, in <module>
    from tensorflow.keras.backend import set_session
ImportError: cannot import name 'set_session' from 'tensorflow.keras.backend' (/usr/local/lib/python3.7/dist-packages/tensorflow/keras/backend/__init__.py)

이슈71번 참고
https://github.com/quantylab/rltrader/issues/71

**Comment by ggokka** [comment]
아, 데탑하고 똑같이 하면 되네요.  현 버전이 언인스톨되면서 다운그레이드 됩니다.
!pip install tensorflow==1.15.2

하지만, 최종 'NoneType' object 에러가 발생하네요.
2021-06-13 01:55:01.648857: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-06-13 01:55:01.653045: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299995000 Hz
2021-06-13 01:55:01.653359: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557fed4c4a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-13 01:55:01.653401: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    for stock_code in args.stock_code:
TypeError: 'NoneType' object is not iterable
