### ISSUE TITLE
main.py 오류 문의입니다.

### ISSUE THREAD

**Issue by termini123** [quantylab/rltrader#125]
python main.py --stock_code 005930 --rl_method dqn --net dnn --learning --num_epoches 100 --lr 0.001 --start_epsilon 1 --discount_factor 0.9
로 main.py(default='v2')로 실행시키면 아래와 같은 에러가 뜹니다.
-----------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)
  File "C:\Users\Computer\anaconda3\lib\site-packages\pandas\core\indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\Computer\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Users\Computer\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
-----------------------------------------------------------------------------------------------------------------------------------------------
사용한 파일은 깃허브에서 바로 받은 파일인데 어떤 부분이 문제인지 전혀 모르겠습니다... 
원래 있던 파일인데 왜 범위가 벗어났다고 뜨는걸까요? 혹시 v2로 설정할 때 main.py와 predict.py말고 수정할 부분이 또 있을까요?

**Comment by quantylab** [comment]
@termini123 
v2 데이터가 2016~2019년까지라서 `start_date`와 `end_date`를 넣어주셔야 합니다.
https://cafe.naver.com/quantylab 가입하시면 v3, v4 데이터 다운받으실 수 있습니다.
