### ISSUE TITLE
코딩 오류

### ISSUE THREAD

**Issue by leehj850212** [quantylab/rltrader#26]
2019-10-11 10:57:05.753075: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
LR: 0.001, DF: 0, TU: [1, 2], DRT: 0.2
C:\Users\PRO\PycharmProjects\RL AI TEST1\RLTRADER\visualizer.py:95: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
  ax.set_xlim(xlim)  # x축 limit 재설정
Traceback (most recent call last):
  File "C:/Users/PRO/PycharmProjects/RL AI TEST1/RLTRADER/main.py", line 61, in <module>
    discount_factor=0, start_epsilon=.5)
  File "C:\Users\PRO\PycharmProjects\RL AI TEST1\RLTRADER\policy_learner.py", line 173, in fit
    initial_balance=self.agent.initial_balance, pvs=memory_pv
  File "C:\Users\PRO\PycharmProjects\RL AI TEST1\RLTRADER\visualizer.py", line 63, in plot
    self.axes[2].plot(x, outvals[:, action], style)
IndexError: too many indices for array

이문제에 대한 해답을 아시는지요?

**Comment by quantylab** [comment]
@leehj850212 안녕하세요.
`IndexError: too many indices for array` 이 에러 메시지만 봤을 때는 outvals가 numpy array가 아닌 것 같은 생각이 듭니다.

https://github.com/quantylab/rltrader/blob/master/visualizer.py#L38

이 부분 확인 부탁드립니다.
