### ISSUE TITLE
numpy가 import가 안되는데 해결방안 조언 부탁드립니다.

### ISSUE THREAD

**Issue by ujujang** [quantylab/rltrader#65]
"C:\Users\David Choi\PycharmProjects\RLTrader\venv\Scripts\python.exe" "C:/Users/David Choi/PycharmProjects/RLTrader/main.py"
Traceback (most recent call last):
  File "C:/Users/David Choi/PycharmProjects/RLTrader/main.py", line 8, in <module>
    import utils
  File "C:\Users\David Choi\PycharmProjects\RLTrader\utils.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Process finished with exit code 1

**Comment by quantylab** [comment]
@ujujang `numpy`가 설치되어 있지 않은 것 같습니다.
`pip list | grep numpy`로 설치 여부를 확인해 보시면 좋을 것 같습니다.

다양한 주요 모듈이 이미 설치되어 있는 Anaconda를 사용하실 것은 추천드립니다.
https://www.anaconda.com/products/individual

**Comment by ujujang** [comment]
아나콘다를 깔았고 charm 프로그램으로 코딩을 했는데도 그러네요. ㅜㅜ
