### ISSUE TITLE
주식데이터만 바꿨는데 오류가 나네요.

### ISSUE THREAD

**Issue by JungsooCho** [quantylab/rltrader#67]
HTS에서 주식데이터만 긁어와서 .csv utf-8로 저장해서 코드를 실행했는데 아래와 같은 에러가 납니다.
혹시, 도움을 받을 수 있을까요?

Traceback (most recent call last):
  File "main.py", line 102, in <module>
    min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)
  File "d:\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "d:\anaconda3\lib\site-packages\pandas\core\indexing.py", line 2138, in _getitem_axis
    self._validate_integer(key, axis)
  File "d:\anaconda3\lib\site-packages\pandas\core\indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

**Comment by quantylab** [comment]
@JungsooCho 안녕하세요. csv 파일의 head (header + N rows) 부분을 함께 보여주시면 이슈 해결에 도움이 될 것 같습니다.

**Comment by JungsooCho** [comment]
학습에 사용한 파일을 첨부드립니다:

[005931.zip](https://github.com/quantylab/rltrader/files/5388773/005931.zip)

**Comment by JungsooCho** [comment]
> @JungsooCho 안녕하세요. csv 파일의 head (header + N rows) 부분을 함께 보여주시면 이슈 해결에 도움이 될 것 같습니다.

학습에 사용한 파일을 첨부드립니다:
[005931.zip](https://github.com/quantylab/rltrader/files/5395521/005931.zip)

**Comment by quantylab** [comment]
다음 이슈 확인 부탁드립니다.

date 컬럼의 포멧을 변경이 필요합니다.
https://github.com/quantylab/rltrader/blob/master/data_manager.py#L126 날짜 형식이 달라서 이 부분에서 데이터가 전부 제거되는 문제가 있습니다. `data_manager.py` 역시 좀더 친절하게 date 값들을 수용하도록 개선 검토하겠습니다.

그런데 데이터가 주봉인가요? 주봉으로도 괜찮은 결과가 나올지 궁금하네요^^ 의미있는 실험 결과가 나오면 가능하시다면 공유도 부탁드립니다.

감사합니다.

**Comment by JungsooCho** [comment]
@quantylab 
답변 감사합니다.

아직 의문이 풀리지 않아 다시 피드백을 구합니다:
날짜형식의 경우, v1 폴더 내 데이터의 날짜형식이 제가 첨부한 데이터의 날짜형식과 다르지 않은데(둘 다 '/'로 구분), v1 폴더 데이터는 왜 같은 오류를 주지 않는 것인지요? 실제로 005930.csv 파일을 학습했을 때 오류없이 학습됐습니다.

한 가지 추가적으로 여쭤볼게, HTS에서 데이터를 추출하면 날짜가 시간의 역순으로 추출되는데 순서를 바로 잡지 않고 학습해도 괜찮은지요? 아니라면, 약간의 코드수정으로 가능한 것인지요?

정확하게 보신대로 주봉으로 데이터를 추출했습니다. 저도 의미있는 결과가 나오길 기대하고 있습니다.

**Comment by quantylab** [comment]
@JungsooCho (정확히는 모르겠지만;;) 파일을 엑셀 등의 프로그램으로 여셔서 그렇게 보여진게 아닐까 생각이 듭니다. 실제 파일에 쓰여져있는 날짜 형식은 https://github.com/quantylab/rltrader/blob/master/data/v1/005930.csv 여기서 확인해 보시면 됩니다.

날짜순 정렬의 경우 데이터 자체에서 정렬되어 있지 않다면 코드에서 한줄 추가가 필요합니다. (단순하게 string 정렬이기 때문에 yyyy-MM-dd 형식을 갖춰야 제대로 정렬이 될 것입니다.)
https://github.com/quantylab/rltrader/blob/master/data_manager.py#L122

**Comment by JungsooCho** [comment]
@quantylab 
답변 감사합니다.

아직도 풀리지 않은 몇 가지 의문이 있습니다:

먼저, 날짜형식은 무슨 프로그램으로 확인하신 건지요?

그리고 말씀하신대로 날짜형식을 yyyy-mm-dd 형태로 수정하여 코드를 재실행했을 때 이번엔 아래와 같은 오류메시지가 출력됐습니다:

Traceback (most recent call last):
  File "main.py", line 99, in <module>
    args.start_date, args.end_date, ver=args.ver)
  File "E:\MyWork\rltrader\data_manager.py", line 119, in load_data
    data.columns = ['date', 'open', 'high', 'low', 'close', 'volume']
  File "d:\anaconda3\lib\site-packages\pandas\core\generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "d:\anaconda3\lib\site-packages\pandas\core\generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "d:\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 7 elements, new values have 6 elements

분명히 데이터는 여섯개의 칼럼이 맞는데, 일곱개를 기대했다는 게 무슨 의미인지 조언부탁드립니다.
혹시 모르니 사용된 데이터 파일을 첨부합니다.
[005931.zip](https://github.com/quantylab/rltrader/files/5413799/005931.zip)

**Comment by quantylab** [comment]
@JungsooCho 일반 텍스트 에디터 (VSCode)로 확인했습니다.
올려주신 데이터를 확인하니 CSV 형식이 아니라 TSV 형식이라 제대로 파싱이 안된 것으로 확인했습니다.
데이터에서 Separator를 `,`로 변경해 주시거나 TSV 형식을 원하신다면 코드에서 `pd.read_csv` 할 때 인자에 `sep='\t'`를 추가해 주시면 됩니다. 감사합니다.

**Comment by JungsooCho** [comment]
@quantylab 
답변 감사합니다.

데이터를 저장할 때 책에서 언급하신대로 '.csv UTF-8'로 저장했는데, 왜 형식이 바뀐 걸까요?

여튼, 말씀해주신대로 sep='\t' 을 인자로 추가하여 다시 실행해봤습니만, 이번엔 아래와 같은 데이터 개수가 안 맞다는 듯한 오류메시지가 발견됐습니다:

NumExpr defaulting to 6 threads.
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    args.start_date, args.end_date, ver=args.ver)
  File "E:\MyWork\rltrader\data_manager.py", line 125, in load_data
    data = preprocess(data)
  File "E:\MyWork\rltrader\data_manager.py", line 78, in preprocess
    / data['close'][:-1].values
  File "d:\anaconda3\lib\site-packages\pandas\core\indexing.py", line 671, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "d:\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1019, in _setitem_with_indexer
    "Must have equal len keys and value "
ValueError: Must have equal len keys and value when setting with an iterable

이번엔 무슨 문제일까요?

**Comment by quantylab** [comment]
@JungsooCho 
정렬 코드 한줄 추가하여 인덱스 값 순서가 변경되면서 문제가 발생한 것으로 보입니다.
https://github.com/quantylab/rltrader/blob/master/data_manager.py#L122 와 같이 수정하면 되겠습니다.

**Comment by JungsooCho** [comment]
@quantylab 
감사합니다. 문제점이 해결됐습니다.
