### ISSUE TITLE
실행오류 문의

### ISSUE THREAD

**Issue by Peter-Hwang** [quantylab/rltrader#71]
master 브랜치를 그대로 받아서 실행해보는데 모듈 import 부분에서 에러가 납니다.

명령어로 책의 가이드 대로 tensorflow, keras는 모두 설치를 했습니다.

 Traceback (most recent call last):
  File "c:\Workspaces\rltrader\main.py", line 66, in <module>
    from learners import DQNLearner, PolicyGradientLearner, \
  File "c:\Workspaces\rltrader\learners.py", line 11, in <module>
    from networks import Network, DNN, LSTMNetwork, CNN
  File "c:\Workspaces\rltrader\networks.py", line 23, in <module>
    from tensorflow.keras.backend import set_session
ImportError: cannot import name 'set_session' from 'tensorflow.keras.backend' (C:\Dev\Anaconda3\lib\site-packages\tensorflow\keras\backend\__init__.py)

어떻게 해결해야 할까요?

**Comment by tmdgus717** [comment]
저도 같은데서 막혔습니다. 혹시 해결 하셨나요??

**Comment by quantylab** [comment]
@Peter-Hwang @tmdgus717 이슈해결을 위해 tensorflow 버전 확인 해보시고 커멘트 남겨주세요.
```py
import tensorflow; tensorflow.__version__
```

**Comment by tmdgus717** [comment]
@quantylab tensorflow version 2.2.0 입니다.

**Comment by tmdgus717** [comment]
@quantylab DQN+CNN 을 이용하여 실행하고 싶은데 mian문의 공통파라미터 설정 common_params 딕셔너리의 값을 바꾸면 되는건가요? 파라미터 설정법을 잘 모르겠습니다.

**Comment by quantylab** [comment]
@tmdgus717 TF 버전은 `1.15.0`을 사용하시길 권장드립니다.
책 출간 당시 `2.0`으로 테스트 했을 때 성능 문제가 있어서 현재는 `1.15.0`을 사용했습니다.

이슈가 해결되었는지 확인해보고 `2.X` 최신 버전 도입을 검토해 보겠습니다.

**Comment by rubyjohn** [comment]
답변도 나왔지만
keras 2.2.4를 설치하면 tf 1.15.0으로 깔립니다.
그냥 새 가상환경에서 keras 2.2.4로 install 하면 될겁니다.

**Comment by kijong-yi** [comment]
혹시 이 이슈에 update가 있는지 궁금합니다. 왜냐하면 2021.06.10 현재 시점에 pip에 1.15.0이 없어진 것 같습니다.

(from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0)
