### ISSUE TITLE
오류 해결이 안됩니다.

### ISSUE THREAD

**Issue by isykan75** [quantylab/rltrader#94]
아래와 같은 에러는 문제가 멀까요?

Traceback (most recent call last):
  File "main.py", line 101, in <module>
    min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1496, in _getitem_axis
    self._validate_integer(key, axis)
  File "C:\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

min_trading_unit = max(int(100000 / chart_data.iloc[-1]['close']), 1)
이 부분이 잘못된걸까요?

**Comment by quantylab** [comment]
@isykan75 out of bounds 에러로 보아 데이터가 비어있는거 같은데 입력으로 사용하신 데이터를 확인해봐야 할 것 같습니다.
