### ISSUE TITLE
main.py 실행오류 

### ISSUE THREAD

**Issue by heunwoo3** [quantylab/rltrader#98]
파이썬,tensoflow   모듈에러 문제는 이제 다해결한것 같은대 계속
2021-05-23 15:21:48.110035: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-05-23 15:21:48.112191: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-05-23 15:21:48.135927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:1c:00.0
2021-05-23 15:21:48.136079: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2021-05-23 15:21:48.139347: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2021-05-23 15:21:48.142735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2021-05-23 15:21:48.145223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2021-05-23 15:21:48.150486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2021-05-23 15:21:48.153976: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2021-05-23 15:21:48.161653: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2021-05-23 15:21:48.161805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-05-23 15:21:48.604223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-23 15:21:48.604324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-05-23 15:21:48.604379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-05-23 15:21:48.604576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6780 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:1c:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:/Users/82109/anaconda3/envs/rltrader/rltrader/main.py", line 94, in <module>
    for stock_code in args.stock_code:
TypeError: 'NoneType' object is not iterable

이런 오류문구가 뜨네요  뭐가 문제일까요

**Comment by seeyoungm** [comment]
저도 
Traceback (most recent call last):
  File "/Users/maengseongho/Documents/python/rltrader/main.py", line 86, in <module>
    for stock_code in args.stock_code:TypeError: 'NoneType' object is not iterable 
라는 오류가 나는데 어떻게 해결 하셨나요?
