### ISSUE TITLE
에러 도움 부탁드립니다.

### ISSUE THREAD

**Issue by ttcoaster** [quantylab/rltrader#99]
network.py 파일에서
if os.environ['KERAS_BACKEND'] == 'tensorflow':
    from tensorflow.keras.models import Model
    from tensorflow.keras.layers import Input, Dense, LSTM, Conv2D, \
        BatchNormalization, Dropout, MaxPooling2D, Flatten
    from tensorflow.keras.optimizers import SGD
    from tensorflow.keras.backend import set_session
    import tensorflow as tf
    graph = tf.get_default_graph()
    config = tf.compat.v1.ConfigProto()
    config.gpu_options.allow_growth = True
    sess = tf.compat.v1.Session(config=config)
Traceback (most recent call last):

  File "<ipython-input-2-12b81f906840>", line 1, in <module>
    if os.environ['KERAS_BACKEND'] == 'tensorflow':

  File "C:\Users\jd091\anaconda64bit\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None

KeyError: 'KERAS_BACKEND'
if 조건문의 os.environ에 KERAS_BACKEND가 없다고 자꾸 에러가 나는데 해결 방법을 잘 모르겠습니다.

**Comment by quantylab** [comment]
@ttcoaster 
KERAS_BACKEND 환경변수는 https://github.com/quantylab/rltrader/blob/master/main.py#L39 여기서 설정해 주고 있습니다. 이부분이 정상적으로 수행되는지 확인해보시는게 좋겠습니다.
